### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by darkperis** [GeneaLabs/laravel-caffeine#141]
Please add support for Laravel 9. Thanks

**Comment by mikebronner** [comment]
Thanks for the reminder, this is now available in version 9.0.0.

**Comment by mikebronner** [comment]
Re-opening this, as we are waiting on downstream dependency.

**Comment by mikebronner** [comment]
This is now released in 9.0.2.

**Comment by hashimaziz1** [comment]
Is Laravel 9 still supported? I ask because doing `composer require` without any version constraints always gives me a package version of `^9.0`, and I'd really like to benefit from recent improvements to the package, especially the [sleep mode fix](https://github.com/mikebronner/laravel-caffeine/pull/138).

**Comment by mikebronner** [comment]
Unfortunately not, because Laravel 9 itself is also no longer supported. See https://laravelversions.com/en

**Comment by hashimaziz1** [comment]
Damn, and I'd only recently updated to Laravel 9. Somehow always behind the curve haha. Thanks for letting me know Mike, and thanks for your work on this package.

**Comment by mikebronner** [comment]
Not a problem, glad you like it! Yea, I still have apps on Laravel 9 -- its a struggle for sure to keep several large apps on the current Laravel version.
