### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by tobysommer** [GeneaLabs/laravel-caffeine#145]
Hi!

First things first: Thanks for this package! 

Can you please add Laravel 10 support.

Thanks in advance and have a nice day!

**Comment by aglipanci** [comment]
@tobysommer theoretically it's should be pretty straight forward, however since this package depends on https://github.com/jenssegers/model which is not actively maintained, it could be challenging.

@mikebronner as far as I have seen you don't depend a lot on `jenssegers/model`, would you be positive to remove it as a dependency from the project. Would you accept a PR for that?

**Comment by mikebronner** [comment]
@aglipanci yea, would love that ... have been considering forking jenssegers/model, as its maintenance is very slow and delayed, if anything happens on it at all

@tobysommer I will be updating my packages over the next several weeks, hope to get to this one sooner than later

**Comment by DariusIII** [comment]
I have forked Jesenger/model so you could use that for time being until the issue is resolved https://github.com/DariusIII/model. I haven't changed anything outside of composer dependencies, so no changes needed anywhere, not even class names and namespaces.

**Comment by RenoLooijmans** [comment]
@mikebronner jenssegers released a new version for his model package. Since we (me) experience issues with the current bypass (dev-master), would it be possible to change it back to his updated version for the meanwhile so we can get this working with Laravel 10?

**Comment by mikebronner** [comment]
@RenoLooijmans  good catch, would you mind submitting a quick PR for that? -- I'm in the middle of something else at the moment, and doing that would really help out :)
