### ISSUE TITLE
External file vs inline script

### ISSUE THREAD

**Issue by koceg** [GeneaLabs/laravel-caffeine#3]
Javascript code here is very small, so it's a shame that we need whole additional http-request to get it.
In terms of client performance it would be better to inline this script, but I don't know how it will affect server-side performance. I have a feeling that it would add less than a millisecond or so, but can't figure out a way to test this assumption reliably.
Another approach would be just add `async` attribute to a script tag, so it won't affect page loading.

**Comment by mikebronner** [comment]
Thanks @koceg  :) I will look into that, good suggestion! :)

**Comment by koceg** [comment]
It may not be necessary at all, since the script is loaded at the very bottom of the page. I'm not sure will it block loading of images, for example.
Anyway, I think `async` attribute won't hurt :) But I wasn't sure about correct syntax for this attribute, turns out there is [some difference](http://stackoverflow.com/a/1834129).

**Comment by mikebronner** [comment]
yea, it won't block anything right now, but the extra HTTP request is kind of annoying. Also, isn't async already set to true?

```js
        request.open('GET', url, true);
```

**Comment by koceg** [comment]
Async ajax-request and async script loading is not the same thing :)

**Comment by mikebronner** [comment]
I see what you mean now. Thanks for clarifying. I don't think that's necessary for this small bit of code, especially now that it's inline.

If it were an external file, or a larger block of code that did some extensive processing, sure. I suspect trying to implement async loading of the tiny inline snippet would reduce load time, rather than optimize it.

But yes, if you can come up with a way to benchmark it, that would be cool. I suppose running it on an empty HTML page measuring microtime would do it?

Seeing that the JS is now inlined, I'll go ahead and close this issue. If you decide to test the async loading, please do report back (and re-open this issue if it will indeed benefit). :+1:

**Comment by koceg** [comment]
Hardcoding script is the best solution from performance standpoint.
It's a little harder to change it now, but I don't think you will do it very often.
